---
- name: install openssl-devel
  dnf:
    name:
      - openssl-devel
      - git
    disable_gpg_check: yes

- name: check ~/.pyenv
  stat:
    path: ~/.pyenv
  register: pyenv

- name: install pyenv
  shell: |
    git clone https://github.com/pyenv/pyenv.git ~/.pyenv
    echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc
    echo 'command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc
    echo 'eval "$(pyenv init -)"' >> ~/.bashrc
  when: not pyenv.stat.exists

  