---
# Apache インストール
- name: install apache
  yum:
    name:
      - httpd
    state: present

- name: modify defconf
  blockinfile:
    dest: /etc/httpd/conf/httpd.conf
    insertafter: '^#ServerName www.example.com:80$'
    content: 'ServerName {{ inventory_hostname }}:80'

- name: mkdir public_html
  file:
    path: "/var/www/vhosts/{{ item.domain }}/public_html"
    state: directory
    owner: "{{ item.customer }}"
    group: apache
    mode: 02775
    recurse: yes
  when: domain_name is defined
  with_items:
    -  "{{ domain_name }}"

- name: add virtualhost
  template:
    src: "../templates/vhost.j2"
    dest: "/etc/httpd/conf.d/vhost.{{ item.domain }}.conf"
    owner: root
    group: root
    mode: 644
  when: domain_name is defined
  with_items:
    -  "{{ domain_name }}"

- name: mkdir custom docment root
  file:
    path: "{{ item.document_root }}"
    state: directory
    owner: "{{ item.customer }}"
    group: apache
    mode: 02775
    recurse: yes
  when: custom_domain is defined
  with_items:
    -  "{{ custom_domain }}"

- name: add custom virtualhost
  template:
    src: "../templates/custom_vhost.j2"
    dest: "/etc/httpd/conf.d/vhost.{{ item.domain }}.conf"
    owner: root
    group: root
    mode: 644
  when: custom_domain is defined
  with_items:
    -  "{{ custom_domain }}"

- name: change parameter
  template:
    src: ../templates/{{ item }}
    dest: /etc/httpd/conf.d/
    owner: root
    group: root
    mode: 0644
  with_items:
    - mpm.conf
    - security.conf

- include: security.yml
